### PR TITLE
Don't write java.lang imports to generated classes

### PR DESCRIPTION
**Pull request by tadamski**
Can we make this change to avoid adding java.lang classes? Seems that new checkstyle versions have problems with that.

### CODE REVIEW

**Comment by dmlloyd** [comment]
I agree with the change generally, however this may trip up in cases where there is a class in the local package with the same name, or a nested class. There might be a way to safely handle these cases (for example, keeping track of the local package classes and nested classes of the current class, and using that information to automatically skip adding the import as needed).

**Comment by tadamski** [comment]
@dmlloyd I'm not sure if I understand correctly. I was indeed able to make another checkstyle failure when using classes from the same package or nested classes but was able to eliminate it with the package check (which I rebased in the PR).

**Comment by dmlloyd** [comment]
For example, let's say I generate code in the same package as a class which shares a name with a `java.lang` class, such as `org.jboss.modules.Module`, and my generated code includes a reference to `java.lang.Module`. We don't want to import the latter in that case IIRC (I don't recall which gets precedence in this case). The existing checks might suffice for this case though; I just wanted to point it out so we could test it.

**Comment by tadamski** [comment]
Ahh ok, this would fail indeed.

**Comment by tadamski** [comment]
@dmlloyd I have refactored the PR so that it JDeparser has an API that allows to provide it with implicit import collection for a given class file. I tried to rely on modifing JSources implementation and usage so that this information can be obtained from it, but this turn out to be too complicated because:
* Sources contains only the classes that are being generated - so I had to extend API for a class that is present but not implemented
* Even after that it is non-trivial to establish correct implicit import for a given classes based on all classes present (f.e. nested classes inherited from parent class)
As a result, I created a solution that is still hacky but is fairly simple and easily implementable: I just calculated list of implicit import for a given use case (in this case logger) and provide jdeparser with it.

**Review by dmlloyd — APPROVED** [review]
Sure, I think this looks fine. Thanks!

**Comment by tadamski** [comment]
Cool, thanks as well!

**Pull request merged**
